apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/keat/.asdf/installs/kompose/1.28.0/bin/kompose -f ../docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9101"
      port: 9101
      targetPort: 9101
    - name: "29092"
      port: 29092
      targetPort: 29092
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
