apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/keat/.asdf/installs/kompose/1.28.0/bin/kompose -f ../docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: connect
  name: connect
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: connect
status:
  loadBalancer: {}
