---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink
  namespace: flink-operator
spec:
  image: flink:1.17
  imagePullPolicy: IfNotPresent
  flinkVersion: v1_17
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  ingress:
    template: "/{{name}}(/|$)(.*)"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/configuration-snippet: if ($uri = "/flink") {rewrite .* $1/flink/ permanent;}
