apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/keat/.asdf/installs/kompose/1.28.0/bin/kompose -f ../docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry-conf
  name: schema-registry-conf
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: schema-registry-conf
status:
  loadBalancer: {}
