apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: schema-registry-conf
  name: schema-registry-conf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry-conf
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/flink-poc-default: "true"
        io.kompose.service: schema-registry-conf
    spec:
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry-conf
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
          image: confluentinc/cp-schema-registry:7.4.0
          name: schema-registry-conf
          ports:
            - containerPort: 8081
          resources: {}
      hostname: schema-registry-conf
      restartPolicy: Always
status: {}
